from . import salamet_patiente
from . import salamet_medecin
from . import salamet_grossesse
from . import salamet_equipe_medicale
from . import salamet_accouchement
from . import salamet_consultation
from . import salamet_notification
from . import salamet_dashboard
from . import salamet_bilan_prenatal